### ISSUE TITLE
nile setup fails

### ISSUE THREAD

**Issue by ccarnino** [OpenZeppelin/nile#63]
Hello team.
I am trying to setup a private key alias as described in the README. but I get an error.

I am on a working installation of Nile on macOS (I followed the macOS specific installations) and I am able to compile and deploy. I created the venv, installed cairo-nile with pip, inited the project. I also create a `.env` file in the root directory with the `YOLO=123` key.

```
> nile setup YOLO    

Traceback (most recent call last):
  File "/opt/homebrew/bin/nile", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/nile/cli.py", line 84, in setup
    Account(signer, network)
  File "/opt/homebrew/lib/python3.9/site-packages/nile/core/account.py", line 20, in __init__
    self.signer = Signer(int(os.environ[signer]))
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'YOLO'
```

I have no idea what is going wrong

**Comment by martriay** [comment]
Weird, I cannot reproduce it. Did you activate the virtualenv? With something like `source env/bin/activate`.

What directory are you running nile from? And where is your `.env`?

**Comment by ccarnino** [comment]
So I have created a venv in the project directory, set the local python version to 3.7.12 (before it was 3.9 which seems not really compatible with nile).
Then I created a `.env` file inside the same root folder with `YOLO=1234`.

Then I run again:
```
❯ nile setup YOLO
🚀 Deploying Account
Got BadRequest
Traceback (most recent call last):
  File "/Users/claudio/Dev/web3/starknet-erc721/env/lib/python3.7/site-packages/services/external_api/base_client.py", line 116, in _send_request
    raise BadRequest(status_code=response.status, text=text)
services.external_api.base_client.BadRequest: HTTP error ocurred. Status: 403. Text: 
Error: BadRequest: HTTP error ocurred. Status: 403. Text: 
Traceback (most recent call last):
  File "/Users/claudio/Dev/web3/starknet-erc721/env/bin/nile", line 8, in <module>
    sys.exit(cli())
  File "/Users/claudio/Dev/web3/starknet-erc721/env/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/claudio/Dev/web3/starknet-erc721/env/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/claudio/Dev/web3/starknet-erc721/env/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/claudio/Dev/web3/starknet-erc721/env/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/claudio/Dev/web3/starknet-erc721/env/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/claudio/Dev/web3/starknet-erc721/env/lib/python3.7/site-packages/nile/cli.py", line 84, in setup
    Account(signer, network)
  File "/Users/claudio/Dev/web3/starknet-erc721/env/lib/python3.7/site-packages/nile/core/account.py", line 28, in __init__
    address, index = self.deploy()
  File "/Users/claudio/Dev/web3/starknet-erc721/env/lib/python3.7/site-packages/nile/core/account.py", line 43, in deploy
    overriding_path,
  File "/Users/claudio/Dev/web3/starknet-erc721/env/lib/python3.7/site-packages/nile/core/deploy.py", line 34, in deploy
    output = subprocess.check_output(command)
  File "/Users/claudio/.pyenv/versions/3.7.12/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/Users/claudio/.pyenv/versions/3.7.12/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['starknet', 'deploy', '--contract', '/Users/claudio/Dev/web3/starknet-erc721/env/lib/python3.7/site-packages/nile/artifacts/Account.json', '--inputs', '883045738439352841478194533192765345509759306772397516907181243450667673002', '--gateway_url=http://localhost:5000/']' returned non-zero exit status 1.
```

So now the error is different, but I am still not able to deploy an account...

**Comment by ccarnino** [comment]
I also tried to export `YOLO=1234` but nothing changed

**Comment by martriay** [comment]
What version of `starknet-devnet` are you running? It seems you're using an outdated one.

**Comment by ccarnino** [comment]
I am running `0.1.17`

**Comment by martriay** [comment]
And what nile version? I'm not being able to reproduce it. What do you get when you manually execute

```sh
starknet deploy --contract /Users/claudio/Dev/web3/starknet-erc721/env/lib/python3.7/site-packages/nile/artifacts/Account.json --inputs 883045738439352841478194533192765345509759306772397516907181243450667673002 --gateway_url=http://localhost:5000/
```

**Comment by ccarnino** [comment]
It fails too:
```
❯ starknet deploy --contract /Users/claudio/Dev/web3/starknet-erc721/env/lib/python3.7/site-packages/nile/artifacts/Account.json --inputs 883045738439352841478194533192765345509759306772397516907181243450667673002 --gateway_url=http://localhost:5000/
Got BadRequest
Traceback (most recent call last):
  File "/Users/claudio/Dev/web3/starknet-erc721/env/lib/python3.7/site-packages/services/external_api/base_client.py", line 116, in _send_request
    raise BadRequest(status_code=response.status, text=text)
services.external_api.base_client.BadRequest: HTTP error ocurred. Status: 403. Text: 
Error: BadRequest: HTTP error ocurred. Status: 403. Text: 
```

But I understood what the issue is. On newer versions of macOS, I think they switched to IPv6 by default, from IPv4. This make processes fail to reach `localhost` but continue to work fine with `127.0.0.1`. So simply changing to the gateway address fixes the issue.
```
❯ starknet deploy --contract /Users/claudio/Dev/web3/starknet-erc721/env/lib/python3.7/site-packages/nile/artifacts/Account.json --inputs 883045738439352841478194533192765345509759306772397516907181243450667673002 --gateway_url=http://127.0.0.1:5000/
Deploy transaction was sent.
Contract address: 0x0044e89874d90a9240b1701ff5e1a467fcf436063d2ecbcfee92dd2c7d3f8696
Transaction hash: 0x1f01358825e06227d33e81fea12d0c2a6128153465635b387fbaf35afe6de4f
```

I would argue that's in the interest of cross platform compatibility to check the codebase and replace every use of `localhost` to `127.0.0.1`.

**Comment by martriay** [comment]
Got it! Thank you very much for the patience and debugging! Will fix.
You also mentioned issues with python 3.9, we're not aware of those. Could you please describe them?

**Comment by ccarnino** [comment]
I deleted the project venv and recreated it. I set python to 3.9.10 and reinstalled cairo-nile as per instructions. Successfully.

But then:
```
❯ nile init             
Traceback (most recent call last):
  File "/Users/claudio/.pyenv/versions/3.9.10/bin/nile", line 5, in <module>
    from nile.cli import cli
  File "/Users/claudio/.pyenv/versions/3.9.10/lib/python3.9/site-packages/nile/cli.py", line 17, in <module>
    from nile.core.version import version as version_command
  File "/Users/claudio/.pyenv/versions/3.9.10/lib/python3.9/site-packages/nile/core/version.py", line 2, in <module>
    from nile import __version__ as nile_version
ImportError: cannot import name '__version__' from 'nile' (/Users/claudio/.pyenv/versions/3.9.10/lib/python3.9/site-packages/nile/__init__.py)

❯ nile compile
Traceback (most recent call last):
  File "/Users/claudio/.pyenv/versions/3.9.10/bin/nile", line 5, in <module>
    from nile.cli import cli
  File "/Users/claudio/.pyenv/versions/3.9.10/lib/python3.9/site-packages/nile/cli.py", line 17, in <module>
    from nile.core.version import version as version_command
  File "/Users/claudio/.pyenv/versions/3.9.10/lib/python3.9/site-packages/nile/core/version.py", line 2, in <module>
    from nile import __version__ as nile_version
ImportError: cannot import name '__version__' from 'nile' (/Users/claudio/.pyenv/versions/3.9.10/lib/python3.9/site-packages/nile/__init__.py)
```

If I repeat the entire process but setting python 3.7.12, then it all works as expected.

**Comment by andrew-fleming** [comment]
> But I understood what the issue is. On newer versions of macOS, I think they switched to IPv6 by default, from IPv4. This make processes fail to reach localhost but continue to work fine with 127.0.0.1. So simply changing to the gateway address fixes the issue.

@ccarnino great call with switching to `127.0.0.1`. I did, however, test out your hypothesis and shut off IPv6 in favor of IPv4 on my Mac. Interestingly, `localhost` still returned `BadRequest`, so I'm not exactly sure why it's behaving in such a way.

**Comment by ccarnino** [comment]
I am not sure exactly what it is. I had the same problem a while ago with a setup of nodejs and nextjs. A friend told me about this issue brut I me we investigated the actual why. 

Claudio

**Comment by andrew-fleming** [comment]
So I found the culprit. MacOS Monterey has AirPlay Receiver running on port 5000 which is why `localhost:5001` works but `localhost:5000` does not. To rectify:
1. Go to _system preferences_ -> _sharing_
2. Untick the AirPlay Receiver box

**Comment by maryhu-2020** [comment]
nile send account-alias doesn't work.

nile send PKEY1 0x05b89eb169c11f591b10ab01c06b86845fd631aafa907906550332c0e457f928 incrementCounter 10

...File "/Users/test/.pyenv/versions/3.9.1/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/test/.pyenv/versions/3.9.1/lib/python3.9/subprocess.py", line 1752, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not int

**Comment by martriay** [comment]
I don't understand isn't that simply a port rather than hostname issue?

**Comment by maryhu-2020** [comment]
if it's port issue, can we have a parameter in command 'nile node' to specify a port that way we can avoid 5000

**Comment by martriay** [comment]
> if it's port issue, can we have a parameter in command 'nile node' to specify a port that way we can avoid 5000

1. it's not a port issue
2. there's a parameter already
